### ISSUE TITLE
野外boss地图换线没有强制回城

### ISSUE THREAD

**Issue by Syifan1** [BeiDouMS/BeiDou-Server#10]
例如：蘑菇王 僵尸蘑菇王， 蝙蝠魔等， map中这些地图都是写的强制回城。但是服务端好像没有支持

**Comment by SleepNap** [comment]
已增加参数CHANGE_CHANNEL_FORCE_RETURN，默认为false，想返回可以设置成true

**Comment by Syifan1** [comment]
您发给我的信件已经收到,我会第一时间给您回复，谢谢您的来信！祝：工作顺利！This is an automatic reply, confirming that your e-mail was received.Thank you
