### ISSUE TITLE
[汉化]瑞恩对话，小地图组件标题

### ISSUE THREAD

**Issue by notsellsunset** [BeiDouMS/BeiDou-Server#101]
![QQ20240901-104115](https://github.com/user-attachments/assets/c2d00544-0cb0-4875-a38a-fece98815ece)
![QQ20240901-104115](https://github.com/user-attachments/assets/adaa5225-aed1-4426-88bf-270fece7b734)

**Comment by notsellsunset** [comment]
![123123](https://github.com/user-attachments/assets/8c350fb8-6683-429a-8f6a-6e2299c4dc66)

**Comment by Doc-Huang** [comment]
这啥意思，我没看明白这位朋友提交的问题

**Comment by TokyoEric** [comment]
1.不是任务，只是个脚本对话，脚本12101，很早前就已经汉化，不知道提问题的同学用的哪个版本的客户端
2.这个图片没有汉化的必要，哪怕现在的GMS083商业服都是默认使用MiniMap和WorldMap，并没有汉化

**Comment by notsellsunset** [comment]
> 1.不是任务，只是个脚本对话，脚本12101，很早前就已经汉化，不知道提问题的同学用的哪个版本的客户端 2.这个图片没有汉化的必要，哪怕现在的GMS083商业服都是默认使用MiniMap和WorldMap，并没有汉化

抱歉，一开始并不知道这是一张图片
