### ISSUE TITLE
[Bug] 骑士三转技能属性攻击好像不起效果

### ISSUE THREAD

**Issue by Syifan1** [BeiDouMS/BeiDou-Server#104]
- [ ] 问题1
属性伤害没效果
**截图/视频**
![yuh6pLlzmn0ck07o](https://github.com/user-attachments/assets/8cf304b0-26d7-47e6-a0dd-43c31a83d2dd)

**如何复现**

- [ ] 问题2

**截图/视频**

**如何复现**

**Comment by leevccc** [comment]
本地测试未发现问题，请补充具体复现过程后再打开issue
