### ISSUE TITLE
[求助] 客户端运行后是否会在电脑产生缓存?

### ISSUE THREAD

**Issue by a346076818886** [BeiDouMS/BeiDou-Server#109]
问题描述
我环境搭建好后, 客户端运行后, C盘少了几个G的内存... 请问是否是客户端或者是服务端引起的..

**Comment by SpicyBurgerKing** [comment]
你是直接在C盘搭建，纯净的服务端大概590m,客户端2G左右。

**Comment by leevccc** [comment]
有可能是交换内存占用的，系统自身的设置。

**Comment by a346076818886** [comment]
> 你是直接在C盘搭建，纯净的服务端大概590m,客户端2G左右。

都不在C盘. 都在D盘搭建的.

**Comment by a346076818886** [comment]
> 有可能是交换内存占用的，系统自身的设置。

但是我重启电脑还是差不多.

**Comment by SleepNap** [comment]
我不知道你说的搭建是指用发行版直接部署，还是搭建开发环境。
如果你用发行版，不会在C盘占用几个G。冒险岛客户端会写一个配置到注册表，服务端不会在C盘生成认为东西。
如果你是搭建开发环境，那么idea首先会在C盘生成文件，整个项目的所有依赖包及依赖源码默认也会下载到C盘。以及前端node相关的东西。以上说的这些开发依赖等东西，有一些是可以配置到其他盘符的。
