### ISSUE TITLE
[Bug] 废弃副本门户可以直接通过，无需完成关卡任务。

### ISSUE THREAD

**Issue by Syifan1** [BeiDouMS/BeiDou-Server#114]
- [ ] 问题1
废弃副本没有完成关卡任务，门户可以直接通过，涉及地图ID103000800-103000803
**截图/视频**
![image](https://github.com/user-attachments/assets/b1551075-b6fb-4aa1-87c6-5194bf1c3ef0)

**如何复现**
如图所示，进入该地图后到门户的位置直接按上。

- [ ] 问题2
玩具副本可能也会出现这个问题，暂时还没去测试过。但是很大概率存在

**截图/视频**

**如何复现**

**Comment by Doc-Huang** [comment]
请问你是如何一个人进入副本的？

**Comment by Syifan1** [comment]
> 请问你是如何一个人进入副本的？

先3开组队进去测试过了。然后用@warp 指令进去截图的

**Comment by g9502995** [comment]
奇怪我这边没问题
![image](https://github.com/user-attachments/assets/e6cbb69d-a359-4f90-893b-4567f115bd01)

**Comment by SleepNap** [comment]
如果北斗没问题那这个问题就关闭，你仔细检查你的map.wz是否改过，少节点了
