### ISSUE TITLE
[Bug] 麦吉的旧战剑任务

### ISSUE THREAD

**Issue by Syifan1** [BeiDouMS/BeiDou-Server#118]
- [ ] 问题1
麦吉的旧战剑任务没有任何提示，wz中也找不到这个任务
**截图/视频**
![b94bb2c025773f4a8d97e1ed0961571](https://github.com/user-attachments/assets/94c59abe-a557-4daa-b036-4ba051521541)

**如何复现**

- [ ] 问题2

**截图/视频**

**如何复现**

**Comment by SleepNap** [comment]
重复了，其他人已经提了，wz叫另外名字

**Comment by SleepNap** [comment]
https://github.com/BeiDouMS/BeiDou-Server/issues/99
