### ISSUE TITLE
[Bug] 转职后飞侠新手任务是木妖，文字提示是绿水灵

### ISSUE THREAD

**Issue by jarecl** [BeiDouMS/BeiDou-Server#122]
- [ ] 问题1
转职后飞侠新手任务是木妖，文字提示是绿水灵
**截图/视频**
![90d7fb8c9e0d3b8cdd0d2efa2f44f584](https://github.com/user-attachments/assets/0056fcf3-172a-4bf7-b16f-c43d038d15be)

**如何复现**

- [ ] 问题2

**截图/视频**

**如何复现**

**Comment by SleepNap** [comment]
客户端已更新
