### ISSUE TITLE
[Bug] 在野外boss地图换线不会回城

### ISSUE THREAD

**Issue by Syifan1** [BeiDouMS/BeiDou-Server#124]
- [ ] 问题1
在野外boss地图换线不会回城；案例地图ID100000005 原版在该地图换线应该是回到射手村，wz也是这么设置的，但是没有效果
**截图/视频**
![image](https://github.com/user-attachments/assets/16c89b82-df50-457c-945b-7d49396219fe)

**如何复现**
到地图ID100000005换线就可以

- [ ] 问题2

**截图/视频**

**如何复现**

**Comment by leevccc** [comment]
配置项 CHANGE_CHANNEL_FORCE_RETURN

**Comment by SleepNap** [comment]
你自己提的issue，已经加了参数，然后又提一个？
https://github.com/BeiDouMS/BeiDou-Server/issues/10

**Comment by Syifan1** [comment]
> 你自己提的issue，已经加了参数，然后又提一个？ #10
= =!!! 啊 忘记了之前提过
