### ISSUE TITLE
[Bug] 商城道具时间bug

### ISSUE THREAD

**Issue by Syifan1** [BeiDouMS/BeiDou-Server#125]
- [ ] 问题1
Commodity.img将商品时间修改成-1，在游戏商城显示是-1购买后商品没显示时间
**截图/视频**
![image](https://github.com/user-attachments/assets/44274f61-d1e5-4f93-bbb3-aa256a904b17)

**如何复现**

- [ ] 问题2

**截图/视频**

**如何复现**

**Comment by SleepNap** [comment]
该问题属于个人更改wz导致，北斗该功能正常
