### ISSUE TITLE
[Bug] 宠物到期不消失&非新手或战士使用单手钝器报错

### ISSUE THREAD

**Issue by SpicyBurgerKing** [BeiDouMS/BeiDou-Server#139]
- [ ] 宠物到期不消失

**截图/视频**
![QQ图片20240309235303](https://github.com/user-attachments/assets/fb3d5f8f-d167-47ab-8802-a779d7dd4272)
**如何复现**
商城购买宠物后装备，下线后待宠物到期后再上线，会发现宠物还在装备，但已变成娃娃，双击娃娃提示结束魔法时间。

- [ ] 战士使用单手钝器报错

**截图/视频**
![1](https://github.com/user-attachments/assets/9080bf81-b39c-4d32-9d5b-e31c2f8ca1f8)

**如何复现**
装备后普通

**Comment by SpicyBurgerKing** [comment]
宠物到期不消失截图错误，
![2](https://github.com/user-attachments/assets/b9926d2d-f46b-4135-8166-ff12d9e7568e)

**Comment by SleepNap** [comment]
宠物到期不消失 @SleepNap 
战士使用单手钝器报错 @SleepNap

**Comment by SleepNap** [comment]
问题2无法复现，可能属于个人问题。暂时关闭，如后续再发现，可在提供复现步骤后定位
