### ISSUE TITLE
[求助] 客户端启动错误码 error code: -2147467259

### ISSUE THREAD

**Issue by shuntan** [BeiDouMS/BeiDou-Server#140]
问题描述：服务端启动后，打开exe文件报错 error code: -2147467259，无论是wine还是虚拟机都启动不了。
设备型号：M2芯片

![WX20240921-011508@2x_副本](https://github.com/user-attachments/assets/b584d165-b5d6-4899-ace8-28b6799b41db)

**Comment by SleepNap** [comment]
wiki有文章：
https://github.com/BeiDouMS/BeiDou-Server/wiki/Mac%E7%94%A8%E6%88%B7%E5%A6%82%E4%BD%95%E5%9C%A8%E8%99%9A%E6%8B%9F%E6%9C%BA%E8%BF%90%E8%A1%8C%E5%8C%97%E6%96%97%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by boli2017** [comment]
哥们，服务端和客户端都能转译运行么？
