### ISSUE TITLE
[Bug] 宠物无法自动加蓝 & 属性面板UI异常

### ISSUE THREAD

**Issue by xianyu-yuyu** [BeiDouMS/BeiDou-Server#153]
- [ ] 问题1   开启自动加蓝，到设定值有回蓝声音  但不会使用药品。

![QQ20240928-184011](https://github.com/user-attachments/assets/b2f3b096-c742-48fa-a900-3eefbd45533b)

https://github.com/user-attachments/assets/53ebc7e8-0897-4604-bf15-2c314eb54197

- [ ] 问题2   属性界面右边缺失一小部分。

**截图**
![QQ20240928-183429](https://github.com/user-attachments/assets/47d6921c-eb51-4c0c-97fe-268def5f288e)

当前使用最新1.5正式版

**Comment by leevccc** [comment]
因为第一个配置，北斗的客户端目前没有适配，只是方便给有能力的人自行适配的。请把第一个配置关掉

**Comment by leevccc** [comment]
第二个问题把破攻改成100w试试

关于这个设定，是为了在大数值下，面板不会出现数值遮挡，所以有两套布局方案。当破攻大于999999时，客户端会使用更宽的布局，否则使用默认布局，但是UI图片只有一套，所以这个地方要么修改破攻的数值，要么替换wz里的图片来适配。

我不记得wz里用的是宽布局的ui还是原始ui了

**Comment by xianyu-yuyu** [comment]
> 因为第一个配置，北斗的客户端目前没有适配，只是方便给有能力的人自行适配的。请把第一个配置关掉

关了第一个配置就更恐怖了，放一个耗蓝技能 用一次药水。

**Comment by xianyu-yuyu** [comment]
> 第二个问题把破攻改成100w试试
> 
> 关于这个设定，是为了在大数值下，面板不会出现数值遮挡，所以有两套布局方案。当破攻大于999999时，客户端会使用更宽的布局，否则使用默认布局，但是UI图片只有一套，所以这个地方要么修改破攻的数值，要么替换wz里的图片来适配。
> 
> 我不记得wz里用的是宽布局的ui还是原始ui了

破功值开到100W以上，可以解决这个问题。

**Comment by leevccc** [comment]
> > 因为第一个配置，北斗的客户端目前没有适配，只是方便给有能力的人自行适配的。请把第一个配置关掉
> 
> 关了第一个配置就更恐怖了，放一个耗蓝技能 用一次药水。
> 
> 上一版端就不会出现这个问题。V12

检查下游戏里的设置，只有MP低于游戏里设置的比例，才会触发吃药任务，然后你第2个配置为true的话，就会自动吃药把蓝补充到99%（参见第5个设置）

**Comment by SleepNap** [comment]
1.修改默认配置为1999999
2.其他问题咨询 @leevccc 确认非问题
