### ISSUE TITLE
[Bug] 怪物先掉血再展示动画

### ISSUE THREAD

**Issue by cnxinan** [BeiDouMS/BeiDou-Server#154]
- [ ] 问题1

![图片](https://github.com/user-attachments/assets/978d27fa-2a58-46d1-ad0e-9ef973d60b62)

本地服务本地客户端，默认配置127.0.0.1
**
![图片](https://github.com/user-attachments/assets/4a29e17b-7def-4462-8cb7-7b7b043c6b61)
**
弓箭手用断魂箭，会出现先掉血再展示施法动画。

**Comment by leevccc** [comment]
这是客户端本来就有的“机制”。客户端方面，非致命问题或者严重影响游戏体验的，请自行修复。
