### ISSUE TITLE
[建议] 优化网页控制台批量操作勾选框

### ISSUE THREAD

**Issue by xiaocaouu6** [BeiDouMS/BeiDou-Server#155]
优化/建议
比如商城管理 和背包管理

**Comment by SleepNap** [comment]
商城管理：
1.增加可勾选按钮
2.增加3个操作按钮：数量、价格、有效期
3.消耗、其他可编辑数量、价格、有效期，其他栏目只能编辑价格、有效期
背包管理：
1.增加可勾选按钮
2.增加数量按钮，只有消耗、其他可编辑数量，其他栏目置灰

**Comment by leevccc** [comment]
商城管理已添加批量编辑功能，可以编辑数量、价格、有效期

**Comment by SleepNap** [comment]
背包暂不处理，该问题关闭
