### ISSUE TITLE
[Bug] GM命令!gachalist 会导致客户端闪退，@gacha 城镇名 取出数据非数据库取出

### ISSUE THREAD

**Issue by kevinx1997z** [BeiDouMS/BeiDou-Server#171]
- [ ] 问题1
GM命令!gachalist 会导致客户端闪退

**截图/视频**

**如何复现**
GM角色使用!gachalist命令 会弹出NPC脚本 下一步之后，游戏客户端关闭。

- [ ] 问题2
@gacha 城镇名 取出数据非数据库取出

**截图/视频**

**如何复现**
@gacha 射手村，该命令取出的道具非数据库取出，而是客户端原先的数据。建议更改为从数据库取出，且公布概率。

**Comment by SleepNap** [comment]
已处理
