### ISSUE TITLE
[建议] 第一次进入时免责声明交互不友好

### ISSUE THREAD

**Issue by TomZhang1997** [BeiDouMS/BeiDou-Server#177]
【现象】
首次进入时，输入账号密码后弹出免责声明，但是不允许点击确定按钮，且右侧没有内容需要下滑。
后续无意中将鼠标焦点到免责声明上，滑轮滚动后允许点击确定

【修改建议】
内容展示完全时允许用户直接点确定。
只有需要拉框的时候去判断是否拉到底。

**Comment by SleepNap** [comment]
修复协议过短导致滚动条消失的问题
