### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by skgift** [BeiDouMS/BeiDou-Server#182]
问题一：【服务端】如果api-docs或swagger-ui任意一个enabled设为false，服务就启动不了
![image](https://github.com/user-attachments/assets/66abfcb6-8792-4daf-8ff9-728aa877367d)

问题二：【客户端】进入地图时中间显示的地图名称为英文
![image](https://github.com/user-attachments/assets/dfd81729-0b8a-406d-9dd8-0a95d9a2979f)

问题三：【客户端】角色能力窗口右边被切割了，物品窗口是正常的
![image](https://github.com/user-attachments/assets/cbd7bef4-3f86-4492-b019-5fab02e5ef18)

问题四：【客户端】小地图标题和世界地图标题最好能汉化
![image](https://github.com/user-attachments/assets/e26ba517-aecc-4759-ba6c-3a346cf48ffc)

**Comment by leevccc** [comment]
关于问题一，正在排查修复

关于问题三，两个解决办法：一是自行修改wz把对应图片改为官方的。二是把破攻值由199999改到1000000即可。具体说明请参考 #153

关于问题二和问题四，自行修改wz即可，目前没那么多精力处理这种繁琐的小细节。欢迎你修改完了提交pr给我们。

**Comment by SleepNap** [comment]
问题一，已修复
四涉及ps图片，可能会修一部分

**Comment by SleepNap** [comment]
问题4已由 @FSweil PS汉化
