### ISSUE TITLE
[Bug] 这黑暗悟空任务接了，怎么头顶还在冒灯

### ISSUE THREAD

**Issue by Doc-Huang** [BeiDouMS/BeiDou-Server#183]
- [ ] 问题1
这黑暗悟空任务接了，怎么头顶还在冒灯。。任务做完了，第二天又再次出现了，这个任务有点讨厌啊，都快成每日任务了。建议修改！
**截图/视频**
![image](https://github.com/user-attachments/assets/d8576819-0f80-497d-95e4-b26d909f788d)

**Comment by maplestory220** [comment]
这个任务是每日任务，24小时更新一次；
不想收到的话修改WZ删除即可。

**Comment by TokyoEric** [comment]
该任务本身就是作为北斗特色的每日任务添加，既然用着BeiDouMS，那就应该去适应它，如果无法适应要么自行修改要么换掉北斗

**Comment by Doc-Huang** [comment]
> 该任务本身就是作为北斗特色的每日任务添加，既然用着BeiDouMS，那就应该去适应它，如果无法适应要么自行修改要么换掉北斗

我不清楚你是哪位，你的观点我不太赞成。既然说要优化，要提建议，那就好好去解读，沉心去修改，不要搞得一副不玩就滚的态度。本身这任务就有问题，都接了还冒灯泡💡，你却说没问题，那么你也似乎有点问题

**Comment by TokyoEric** [comment]
> > 该任务本身就是作为北斗特色的每日任务添加，既然用着BeiDouMS，那就应该去适应它，如果无法适应要么自行修改要么换掉北斗
> 
> 我不清楚你是哪位，你的观点我不太赞成。既然说要优化，要提建议，那就好好去解读，沉心去修改，不要搞得一副不玩就滚的态度。本身这任务就有问题，都接了还冒灯泡💡，你却说没问题，那么你也似乎有点问题

该任务定位为北斗特色系列每日活动任务，当天完成当天灯泡会消失，次日会继续出现，这是符合每日任务的定义
其次请注意语气，我并未给予不玩就滚的态度答复你，请勿给我乱扣帽子，我并不欠你什么？
似乎你对此有很大不满，我的意思仅是如果你有更好的想法，可以自行提交pr修改该任务或者考虑移植其他开源项目的任务WZ，祝一切顺利！

**Comment by SleepNap** [comment]
问题已转移到新需求，在新需求上跟踪
https://github.com/BeiDouMS/BeiDou-Server/issues/210

**Comment by ziqiming** [comment]
<img width="687" height="300" alt="Image" src="https://github.com/user-attachments/assets/906163be-dd54-42c3-a761-3c67ead0762d" />
你看看NPC的名字，还不知道他是哪位，，能在这里主动回答你问题的大概率就是参与开发者。尊重别人就是尊重自己哦兄弟
