### ISSUE TITLE
[Bug] 刀飞三转技能落叶斩技能

### ISSUE THREAD

**Issue by qq55595** [BeiDouMS/BeiDou-Server#186]
- [ ] 问题1刀飞三转技能落叶斩技能 描述瞬间攻击三只怪物，实际放技能只能攻击一只

**截图/视频**
![image](https://github.com/user-attachments/assets/d9219093-1336-4b26-b840-c25388c487af)

**如何复现**

- [ ] 问题2

**截图/视频**

**如何复现**

**Comment by s807510951** [comment]
骑士的连环环破技能也是这样，技能描述是攻击三只怪，实际只能攻击一只。

**Comment by SleepNap** [comment]
落叶斩和连环环破都是单体攻击，已修改技能描述
