### ISSUE TITLE
[建议] 建议增加副本可以单人进入的开关

### ISSUE THREAD

**Issue by Doc-Huang** [BeiDouMS/BeiDou-Server#188]
优化/建议
建议增加副本可以单人进入的开关(可以在客户端或者服务端的文本里进行修改调试后即可单人进入)
同时最好能有一并优化一些副本需要多人同时操作的关卡，让单人能够通过或者跳过。
副本单人化可以增加游戏的体验，非常想要尝试！

**Comment by youte0730** [comment]
强烈建议 不然没办法测试

**Comment by SleepNap** [comment]
加入后期规划

**Comment by maplestory220** [comment]
既然作者回复了，也小小期待一下；
不过现阶段完全是自己修改一下脚本也可以达到这个效果；
只需要修改event文件夹内的脚本即可。
