### ISSUE TITLE
[Bug] 应该是分辨率错误

### ISSUE THREAD

**Issue by q791014690** [BeiDouMS/BeiDou-Server#190]
- [ ] 问题1
应该是分辨率错误
**截图/视频**
![2b373b608be0c7dbd47441a550657aef](https://github.com/user-attachments/assets/7945a561-a457-4bce-b5cf-019b39d6faa5)

**如何复现**

- [ ] 问题2

**截图/视频**

**如何复现**

**Comment by TokyoEric** [comment]
不是解析错误，地图背景为原800*600，目前的宽屏分辨率不适配
