### ISSUE TITLE
[Bug] 创建角色界面左侧”查看所有角色“按钮无效 & 建议新增无敌GM命令，方便过图测试

### ISSUE THREAD

**Issue by q791014690** [BeiDouMS/BeiDou-Server#196]
- [ ] 问题1

**截图/视频**

**如何复现**

- [ ] 问题2

**截图/视频**

**如何复现**

**Comment by SleepNap** [comment]
!hide 无敌+隐身

**Comment by Magical-H** [comment]
创建角色界面左侧”查看所有角色“按钮无效
查看所有角色仅在选择世界、选择频道、选择角色时可点击，其它时候默认是禁用的。
