### ISSUE TITLE
[Bug] 127.0.0.1:8686/account/player角色管理界面 发送道具无效（不是自定义装备）

### ISSUE THREAD

**Issue by q791014690** [BeiDouMS/BeiDou-Server#198]
- [ ] 问题1
RT
**截图/视频**

**如何复现**

- [ ] 问题2

**截图/视频**

**如何复现**

**Comment by TokyoEric** [comment]
请附上服务端报错截图，问题描述清晰

**Comment by Doc-Huang** [comment]
本身确实存在这个问题，你发放个药水啊、战利品啊没问题的，你输入那些武器装备的ID根本就发布出来。
这个还用截图吗？真不知道这位“东京”大佬有没有实测过，说的这么清楚了居然还不懂？？

**Comment by Magical-H** [comment]
> 本身确实存在这个问题，你发放个药水啊、战利品啊没问题的，你输入那些武器装备的ID根本就发布出来。 这个还用截图吗？真不知道这位“东京”大佬有没有实测过，说的这么清楚了居然还不懂？？
 
装备需要在自定义装备选项里发放，道具仅仅只能发放道具。
如果输入的ID服务端不存在，则不会发放到背包里。

**Comment by TokyoEric** [comment]
> 本身确实存在这个问题，你发放个药水啊、战利品啊没问题的，你输入那些武器装备的ID根本就发布出来。 这个还用截图吗？真不知道这位“东京”大佬有没有实测过，说的这么清楚了居然还不懂？？

未针对你个人，戾气不要这么重，我仅希望提问人附上报错并描述清晰，以便更准确的复测并回答他

**Comment by SleepNap** [comment]
北斗限制了
发送道具不允许输入装备
发送装备不允许输入道具

1.发送装备已包含发送默认属性的装备，发送装备时，会将装备的默认属性回填界面，如果不做修改直接发送，就是默认属性的装备，如果想修改属性直接修改后发送。
2.发送道具允许修改数量，装备的数量只能是1
因此，将上述功能做了限制，避免了功能混淆
