### ISSUE TITLE
[Bug] 部分未汉化

### ISSUE THREAD

**Issue by q791014690** [BeiDouMS/BeiDou-Server#201]
- [ ] 问题1
属性点积累到一定数量都不点会出现
**截图/视频**
![QQ20241019-044715](https://github.com/user-attachments/assets/7d1a6633-75f7-4b78-82b6-099fd90e2ec9)

**如何复现**

- [ ] 问题2
未汉化
**截图/视频**
![未汉化](https://github.com/user-attachments/assets/8d72f715-1eca-4860-a409-a4ba969c0258)

**如何复现**

**Comment by SleepNap** [comment]
问题2已修复
