### ISSUE TITLE
[建议] 添加GM命令地图码移动，以及全部地图码，以方便测试使用

### ISSUE THREAD

**Issue by q791014690** [BeiDouMS/BeiDou-Server#202]
优化/建议
添加GM命令地图码移动，以及全部地图码，以方便测试使用

**Comment by Magical-H** [comment]
已有GM指令可以移动到指定ID地图。
聊天窗发送  `!warp 地图ID`，地图ID自行查询，控制台带有查询地图ID的功能，也可使用其他方式查询

其他指令发送   `!help`   进行查看

**Comment by SleepNap** [comment]
1.你可以在wz下面直接搜
2.你可以拉最新代码，用控制台搜
3.关于怎么跳转地图，你可以用warp指令，如果你只知道npcId，不知道在哪个地图，可以用warptolife指令
