### ISSUE TITLE
[Bug] 学院组队技能buff服务端报错

### ISSUE THREAD

**Issue by TokyoEric** [BeiDouMS/BeiDou-Server#205]
- [ ] 问题1
学院系统，组队增益buff服务端报错
**截图/视频**
![bad3a9a3785187854377d442217ea137](https://github.com/user-attachments/assets/626dd8a5-c60e-4bca-bb5d-aea550138ba3)
![f2e96f3e3173ae3af31dbc8459e39da6](https://github.com/user-attachments/assets/fb4e0664-bf85-4045-998f-5b417b37f5e3)
**如何复现**
两个角色组队，其中一个开学院组队buff增益会导致角色卡死并离线，服务端报上述错误并卡死无法接入新连接，如web端也无法链接，只能被迫强制关闭服务端，然后回档

- [ ] 问题2

**截图/视频**

**如何复现**

**Comment by SleepNap** [comment]
1.商城Commodity.img，可能存在服务端和客户端不一致的商品
2.学院功能已修复

**Comment by SleepNap** [comment]
1.商城错误是购物车导致，已修复：https://github.com/BeiDouMS/BeiDou-Server/pull/206
