### ISSUE TITLE
[Bug] 青苹果乐园-番茄田传送门无效

### ISSUE THREAD

**Issue by TomZhang1997** [BeiDouMS/BeiDou-Server#209]
![qpg](https://github.com/user-attachments/assets/ece871e8-922f-48ac-8ffa-86b040c8ec26)
这里希娜这边应该有个传送门，角色到青苹果乐园后  到这里就走不掉了  卡图了相当于

**Comment by TomZhang1997** [comment]
破防了兄弟，我玩了两个人物都卡在这里出不去。。瞬移石头也用不了   不说了打大乱斗去了

**Comment by TomZhang1997** [comment]
这边建议是加上一个防卡图机制，在每日任务的菜单栏提供一个传送回明珠港/射手村的选项

**Comment by SleepNap** [comment]
已修复
