### ISSUE TITLE
[Bug] 云彩公园的 斯皮罗纳的烦心事 任务 月光和日光精灵任务数量下线会重置

### ISSUE THREAD

**Issue by li-coder-313** [BeiDouMS/BeiDou-Server#211]
斯皮罗纳的烦心事 任务 月光和日光精灵任务数量下线会重置
遇到过一次反复上下线后这个任务的要求中的月光和日光精灵会一直重置 ，但是星光精灵并没有重置。 这个是正常的吗？

 如下图：
重新上线后 变成了0 (打了一个)
![6A3305B69FE16EB4435E8922EDB1E0E3](https://github.com/user-attachments/assets/ca5613f0-08d8-4bfd-9b1f-1f897bdef1dd)

原先
![D94DCEFD9FF5DD75769D5185C0442DF2](https://github.com/user-attachments/assets/d82ca8e7-9121-4ff0-9a8c-8da384fbea32)

**Comment by Doc-Huang** [comment]
类似的，那个安灵师的勋章任务，打僵尸猴、恶魔之父、恶魔之母、木乃伊犬、大幽灵各444只，这个任务除了僵尸猴其他怪物下线也会重置任务进度。

**Comment by Doc-Huang** [comment]
女神的宠物任务也是，重进后数量会重新统计
![image](https://github.com/user-attachments/assets/202c2928-0e3e-4b06-805a-96f7a87ee0d0)

**Comment by SleepNap** [comment]
已修复

**Comment by Doc-Huang** [comment]
![image](https://github.com/user-attachments/assets/b05df8ec-d387-4596-815b-e7d5e5b8ad5e)
 很多任务貌似都会下线重置数量，这是个例还是系统性问题，是否都修复了？
