### ISSUE TITLE
[求助] 阿里云ECS  windows部署后客户端选人报错

### ISSUE THREAD

**Issue by TomZhang1997** [BeiDouMS/BeiDou-Server#212]
问题描述
将服务端部署到阿里云ECS windows服务器后，可以登录并注册，但是选【开始游戏】会与服务器失去连接
已经按照wiki将客户端的外网IP进行配置
我自己的电脑可以通过公网连接选人进去到地图里面
但是我的同事跟我使用同样的客户端配置，就会卡在选人界面。同事telnet 7575端口能通

服务器端日志：
![baocuo](https://github.com/user-attachments/assets/c3cb1be7-ea9c-4042-a346-93dd5c38e9d7)

我同事的报错
![baocuo1](https://github.com/user-attachments/assets/b8a3a10f-685f-46e8-ba54-ba86759efd6b)

目前客户端没有日志，难以定位问题，服务端的问题倒是可以根据日志去整

**Comment by Magical-H** [comment]
请检查外网端口是否开放

**Comment by TomZhang1997** [comment]
> 请检查外网端口是否开放

我理解对于服务器来说端口是开放了的，假如没开放，我的客户端也连不上才对。
那么对于同事的客户端机器，是要如何检查外网端口是否开放呢？？

**Comment by Magical-H** [comment]
> > 请检查外网端口是否开放
> 
> 我理解对于服务器来说端口是开放了的，假如没开放，我的客户端也连不上才对。 那么对于同事的客户端机器，是要如何检查外网端口是否开放呢？？

我telnet你的8484，7575端口均不通

**Comment by TomZhang1997** [comment]
> > > 请检查外网端口是否开放
> > 
> > 
> > 我理解对于服务器来说端口是开放了的，假如没开放，我的客户端也连不上才对。 那么对于同事的客户端机器，是要如何检查外网端口是否开放呢？？
> 
> 我telnet你的8484，7575端口均不通 可能你对自己的IP做了白名单，别的IP没有做白名单吧

白名单是对所有机器开放的  这点我很确信

**Comment by Magical-H** [comment]
![image](https://github.com/user-attachments/assets/5c3a3ce2-ad7f-4398-bf38-03152c9036d1)

**Comment by TomZhang1997** [comment]
> > > 请检查外网端口是否开放
> > 
> > 
> > 我理解对于服务器来说端口是开放了的，假如没开放，我的客户端也连不上才对。 那么对于同事的客户端机器，是要如何检查外网端口是否开放呢？？
> 
> 我telnet你的8484，7575端口均不通 可能你对自己的IP做了白名单，别的IP没有做白名单吧



> ![image](https://private-user-images.githubusercontent.com/180967876/380198832-5c3a3ce2-ad7f-4398-bf38-03152c9036d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NzA5NjAsIm5iZiI6MTcyOTg3MDY2MCwicGF0aCI6Ii8xODA5Njc4NzYvMzgwMTk4ODMyLTVjM2EzY2UyLWFkN2YtNDM5OC1iZjM4LTAzMTUyYzkwMzZkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxNTM3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTNlNzc4MzJiMmJjMjZiNGY4MTVhMjI5OWViOWViY2Y3YzI3MzI4MzAzMWZkZjBkNWQyYjA4N2ZkN2I3MjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wYtpHTuzoUQjChzXiYblW9Nbta8voLzUMEtBX5jbFfw)
> 
> 很明显是你同事网络的问题，让他重启光猫和路由

感谢大佬指点！同事重启路由器后ok了！
