### ISSUE TITLE
[Bug] 游戏界面右上角BUFF显示问题

### ISSUE THREAD

**Issue by maplestory220** [BeiDouMS/BeiDou-Server#216]
- [ ] 问题1

<img width="614" alt="微信图片_20241027111252" src="https://github.com/user-attachments/assets/1e6cbd3b-2a41-491c-b7ea-314bd44d5d29">

商城购买【双倍经验卡】【双倍爆率卡】可以正常显示。
捡取怪物卡片之后，会导致BUFF消失。

主要影响：挂机的时候不知道BUFF是否处于生效。

**Comment by SleepNap** [comment]
双倍本没有buff展示，此为heavenMS特有，因此占用了其他buff栏位。后续考虑添加参数，双倍是否显示buff。
