### ISSUE TITLE
[Bug] 勋章问题

### ISSUE THREAD

**Issue by q791014690** [BeiDouMS/BeiDou-Server#226]
- [ ] 问题1
达成总数应该不是10
**截图/视频**
![477BFF5D9051AE2A1C43842B31C2DD32](https://github.com/user-attachments/assets/4be47ca4-6889-49bb-b32d-51a776552ecd)

**如何复现**

- [ ] 问题2

**截图/视频**

**如何复现**

**Comment by q791014690** [comment]
> * [ ]  问题1
>   达成总数应该不是10
>   **截图/视频**
>   ![477BFF5D9051AE2A1C43842B31C2DD32](https://private-user-images.githubusercontent.com/185299956/381527263-4be47ca4-6889-49bb-b32d-51a776552ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDc3MDQsIm5iZiI6MTczMDM0NzQwNCwicGF0aCI6Ii8xODUyOTk5NTYvMzgxNTI3MjYzLTRiZTQ3Y2E0LTY4ODktNDliYi1iMzJkLTUxYTc3NjU1MmVjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwNDAzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTliMjZiODg2YzAyMmExNTkyNGEyNmZkZjFhY2VhMTU1NGRmZDIzMjg1OWYxZDdmZWRmM2JjYmQ5NjU5NjA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2wmumUdCKpjd_dAohKlW_-UF2-liKjH3zJ4NvHI4IMA)
> 
> **如何复现**
> 
> * [ ]  问题2
> 
> **截图/视频**
> 
> **如何复现**

米纳尔森林勋章12/10也无法完成任务（超额）的确有问题！

**Comment by SleepNap** [comment]
问题1：
存在相同地图240020101和240020102，以及240020401和240020402，这2个都是隐藏地图，正常进入只会进入01这2张图，进不去02这2张图。目前不知道为什么做2张一样的地图，但除了用gm指令，该问题永远不会发生。
问题2：
因为你超过了进度10，所以无法完成任务，你需要下线去数据库，把27016对应的进度改成10即可。

非问题，暂不处理
