### ISSUE TITLE
[需求] 可设置升级技能点数，属性点数

### ISSUE THREAD

**Issue by q791014690** [BeiDouMS/BeiDou-Server#227]
- **背景**
添加可设置升级技能点数，属性点数选项
**截图/视频**

**背景介绍**

- **需求**

**截图/视频**

**需求介绍**

**Comment by SleepNap** [comment]
你可以先用gm指令@ap 和 @sp

**Comment by q791014690** [comment]
> 你可以先用gm指令@ap 和 @sp

并非这个本意，是控制职业升级获得AP和SP

**Comment by SleepNap** [comment]
知道，可以考虑

**Comment by SleepNap** [comment]
已实现
