### ISSUE TITLE
提示MWLB账户无法进行。无法攻击。

### ISSUE THREAD

**Issue by bigfuji** [BeiDouMS/BeiDou-Server#242]
聊天栏中提示 MWLB账户无法进行。无法攻击。

**截图/视频**
![image](https://github.com/user-attachments/assets/15c8d513-6402-46f4-b9a2-f3e4ead64cf3)
如何复现：
使用网页给玩家发放GM等级，然后开启飞行，退出重新登陆，就可以复现。

- [ ] 问题2

**截图/视频**

**如何复现**

**Comment by bigfuji** [comment]
原来 napms是可以的，而且现在没有了!xiguai这个命令。

**Comment by bigfuji** [comment]
重新试了一下之前那个083cn的客户端，不会出现这种问题。

**Comment by SleepNap** [comment]
1.飞行模式本来无法攻击
2.在正式版发布会说过了，不会做魔改，也不会做吸怪等作弊功能
