### ISSUE TITLE
[求助] 小白求助，服务端IP在哪里修改

### ISSUE THREAD

**Issue by zhienzhien88** [BeiDouMS/BeiDou-Server#249]
问题描述
exe下的三个IP以及config文件的IP都已经改成我的局域网/外网IP了，但是还是卡在角色选择界面（包括我自己）。
请问服务端的IP需要修改吗，需要的话应该在哪个文件下面修改？
如果不需要的话可能是哪里出问题了，或是我自己操作失误？
小白想和朋友联机，找了很久真的找不到解决办法，不好意思麻烦大家了。
如果不好解决的话，辛苦和我说一下解压了两端之后应该做什么也行。

**Comment by zhienzhien88** [comment]
![1734372755998](https://github.com/user-attachments/assets/9a624c88-af9a-4b28-af42-cb0deb81abac)

**Comment by SleepNap** [comment]
application.yml

**Comment by zhienzhien88** [comment]
> application.yml
好嘞，谢谢大佬，一会我回去再找找看，如果方便的话可以告知一下怎么改吗？
如果我没记错的话我没找到IP地址那一栏。

**Comment by SleepNap** [comment]
根据你上面的描述，你应该是看过部署视频的，但如果你看过部署视频，不应该有此疑问。因为视频里已经示范过改服务端ip。

**Comment by SleepNap** [comment]
不对，你用的到底是北斗还是2.x，根据你的描述，exe下的3个ip是用stredit编辑的ip。
如果你仔细看视频，我在视频中讲过，北斗不能用stredit编辑ip

你把这个文档好好看看
https://github.com/BeiDouMS/BeiDou-Server/wiki/%E9%97%AE%E9%A2%98%E6%B8%85%E5%8D%95
