### ISSUE TITLE
任务BUG&汉化

### ISSUE THREAD

**Issue by TokyoEric** [BeiDouMS/BeiDou-Server#25]
60任务，头顶灯泡The Rumor in the Sea of Fog，点击接受无反应，灯泡不消失
![AgAABTXuYAWBsFjuKIxDOokMnSODZzHJ](https://github.com/user-attachments/assets/e24e64c4-d991-4b3a-a61e-4f428710364c)
魔法密林NPC-易德脚本未汉化
![image](https://github.com/user-attachments/assets/79402cba-d1aa-482e-a0eb-a98d4b4ff8bc)
勋章老人任务未汉化
![3](https://github.com/user-attachments/assets/90030551-2fbc-42db-88c8-f3d71392b4b1)
林中之城记忆者、萨比特拉玛、克里斯拉玛任务未汉化
![4](https://github.com/user-attachments/assets/946f4577-22d6-4259-b39b-a41f73c98041)
![5](https://github.com/user-attachments/assets/f698a835-9d10-4f6d-a0ce-02737468c39d)
![6](https://github.com/user-attachments/assets/f6f7cf0b-3986-490d-af89-bea857017d28)
魔法密林巴缇任务未汉化
![7](https://github.com/user-attachments/assets/06d83b74-a2e1-4758-944e-745e155b3e1b)
废弃都市克里斯未汉化
![8](https://github.com/user-attachments/assets/00086dd8-12c7-4ec1-9429-aa0767094028)
蘑菇城警卫队长任务 内幕的事件 点击接受无反应
![9](https://github.com/user-attachments/assets/431ecb86-3f80-4648-9419-ad365a3d4562)
蘑菇城 奇拉蘑菇袍子2 点击使用无效
![10](https://github.com/user-attachments/assets/46bb3147-0dab-4f68-a76e-b6f21f235754)
![11](https://github.com/user-attachments/assets/be544743-ff19-49e0-9216-e6986455e179)

**Comment by huash** [comment]
第2条 魔法密林NPC-易德脚本 [[omddlee](https://github.com/BeiDouMS/BeiDou-Server/pull/13)已汉化

**Comment by huash** [comment]
第6条 废弃都市克里斯 [Tomddlee](https://github.com/BeiDouMS/BeiDou-Server/pull/15)已汉化

**Comment by SleepNap** [comment]
1.60任务，头顶灯泡The Rumor in the Sea of Fog，点击接受无反应，灯泡不消失 @SleepNap @SpicyBurgerKing @leevccc 
3.勋章老人任务未汉化 @SpicyBurgerKing @stanx5 
4.林中之城记忆者、萨比特拉玛、克里斯拉玛任务未汉化 @huash @TokyoEric @yainse 
5.魔法密林巴缇任务未汉化 @huash @TokyoEric @yainse 
7.蘑菇城警卫队长任务 内幕的事件 点击接受无反应 @leevccc @SpicyBurgerKing 
8.蘑菇城 奇拉蘑菇袍子2 点击使用无效 @leevccc @SpicyBurgerKing

**Comment by TokyoEric** [comment]
第4条 林中之城记忆者、萨比特拉玛任务已汉化，克里斯拉玛道具制作脚本已汉化
第5条 魔法森林巴缇任务已汉化

**Comment by SleepNap** [comment]
问题1不存在或已修复

**Comment by SleepNap** [comment]
问题3已修复
