### ISSUE TITLE
[求助] docker部署问题求助

### ISSUE THREAD

**Issue by khg123** [BeiDouMS/BeiDou-Server#251]
问题描述
在BeiDou_MS/gms-server下没看到有docker目录
![1](https://github.com/user-attachments/assets/9ea360e4-ea57-4395-bfb6-5d525596247b)
![2](https://github.com/user-attachments/assets/6ad3ed6a-79f9-438c-b085-66bf9ad794b4)

**Comment by shinobi9** [comment]
迁移到 `BeiDou-docker` 这个仓库了
