### ISSUE TITLE
功能报错或无反应

### ISSUE THREAD

**Issue by TokyoEric** [BeiDouMS/BeiDou-Server#26]
枪战士技能-神圣之火 使用后显示最大血量增加，但使用药水无法满血
![12](https://github.com/user-attachments/assets/f2f203ba-d99f-48d8-b79e-90160d64ab0e)
废弃网吧-自动售货机无法使用，有对应物品，点击无效没反应
![13](https://github.com/user-attachments/assets/9f330d28-21ed-413c-9efb-ac60980cb134)
学院功能无反应
![14](https://github.com/user-attachments/assets/2c1276a3-239a-4cbd-8d0a-e7453f95fa6e)
家族扩容无反应
![16](https://github.com/user-attachments/assets/a9b4c9ec-dc38-4e13-96b5-c28a5bbbb4b9)
风灵使者技能风影漫步，使用后无法取消隐身状态
![17](https://github.com/user-attachments/assets/df007c09-a7c7-461e-a6bd-0433136da2b0)

新增一个拍卖功能，爆率查询（查怪物掉落，查物品掉落）

**Comment by SleepNap** [comment]
1.枪战士技能-神圣之火 使用后显示最大血量增加，但使用药水无法满血 已修复
2.废弃网吧-自动售货机无法使用，有对应物品，点击无效没反应 @leevccc 
3.学院功能无反应 @SleepNap 
4.家族扩容无反应 @SleepNap 
5.风灵使者技能风影漫步，使用后无法取消隐身状态 @SleepNap

**Comment by SleepNap** [comment]
问题5不存在，请检查是否是最新版，或者检查自己是不是gm，如果是gm，gm的隐身不会随技能消失而解除

**Comment by huash** [comment]
2.废弃网吧-自动售货机无法使用，有对应物品，点击无效没反应 已修复

**Comment by SleepNap** [comment]
3.学院功能问题不存在或已修复
4.家族扩容已修复
