### ISSUE TITLE
怪物卡、物品介绍换行、物品叠堆数量、汉化

### ISSUE THREAD

**Issue by TokyoEric** [BeiDouMS/BeiDou-Server#35]
1、怪物卡片有些地方的是拾取在消耗栏里，有些是直接登记的

2、物品详细介绍无法自动换行，导致大部分物品都无法正常显示完整的介绍
![1](https://github.com/user-attachments/assets/f907e7fd-0d52-4eb8-930c-5bda07c75b36)
![2](https://github.com/user-attachments/assets/0964b2c5-4a75-4322-88e5-09a6bb9c1a0c)

3、冬青，脚本汉化
![3](https://github.com/user-attachments/assets/dd3a629b-36dd-4fe7-ae3b-1d8160c176af)

4、增加web控制台消耗栏、其他栏物品叠堆数量配置？
![4](https://github.com/user-attachments/assets/d7452123-c264-41dd-8b41-4d28eb582999)
![5](https://github.com/user-attachments/assets/8a5b5058-20fa-4469-833f-57f91a8b9592)

**Comment by SleepNap** [comment]
1、怪物卡片有些地方的是拾取在消耗栏里，有些是直接登记的 @SpicyBurgerKing @leevccc @SleepNap 
2、物品详细介绍无法自动换行，导致大部分物品都无法正常显示完整的介绍 @SpicyBurgerKing @leevccc 
3、冬青，脚本汉化 @TokyoEric @yainse @huash 
4、增加web控制台消耗栏、其他栏物品叠堆数量配置 @SleepNap

**Comment by leevccc** [comment]
1. 设定是拾取后自动使用，可拾取是玩家擅自更改客户端或者使用了别人的wz导致的。除非对客户端检测，否则无法控制。拾取后也无法使用。
2. 自动换行问题暂时无法通过客户手段解决，只能自行修改String.wz

**Comment by SleepNap** [comment]
4.增加参数ITEM_SLOT_MAX，设置消耗栏和其他栏的物品最大堆叠，默认-1维持原样

**Comment by huash** [comment]
3、冬青，脚本汉化 client已修复
