### ISSUE TITLE
百宝箱的文本有错误 射手村集市NPC比休斯未汉化

### ISSUE THREAD

**Issue by Jesse455823** [BeiDouMS/BeiDou-Server#36]
![QQ截图20240813214009](https://github.com/user-attachments/assets/a959d86d-9193-4477-82b0-b23bc490c42b)
![QQ截图20240813214020](https://github.com/user-attachments/assets/9f969044-1067-4b6c-a973-22085fe5b22c)

![QQ截图20240813214039](https://github.com/user-attachments/assets/e9a5b7ca-06e6-4e02-b99d-7bf8a22f5eb0)

**Comment by leevccc** [comment]
你这个问题无法复现，服务端有错误日志吗？

**Comment by Jesse455823** [comment]
> 你这个问题无法复现，服务端有错误日志吗？

知道问题了 背包满了卸不下 可以在聊天框增加一个背包满了的提示

**Comment by huash** [comment]
![QQ截图20240813223244](https://github.com/user-attachments/assets/e2a2027d-d387-4cf5-9c18-89e02db6dce1)
![QQ截图20240813223320](https://github.com/user-attachments/assets/3bd42c3d-7886-4c8a-9fa7-46fbd0ee1bf7)
汉化问题已修复
