### ISSUE TITLE
新手任务 麦加的最后修炼 任务要求与实际地图怪物不符 且击败怪物任务不累计

### ISSUE THREAD

**Issue by Jesse455823** [BeiDouMS/BeiDou-Server#4]
![QQ截图20240803232138](https://github.com/user-attachments/assets/f7345fb0-2a0a-4922-bc29-7a0e793decdd)

**Comment by huash** [comment]
# #20 
服务端已修复,客户端Check.img和QuestInfo.img还需要改下相关内容

**Comment by SleepNap** [comment]
服务端和客户端都已修复
