### ISSUE TITLE
管理端装备发放问题

### ISSUE THREAD

**Issue by Tomddlee** [BeiDouMS/BeiDou-Server#43]
前置条件 
管理端发放装备【id:1102163 贵族披风】
现象
控制台提示装备发放成功，客户端提示已发放XXX装备，
背包栏占位，出现无图片装备，鼠标移到该物品，端闪退

**Comment by SleepNap** [comment]
服务端是有校验物品是否存在，来判定是否能发放的
该问题是引入String.wz汉化时，引入的String.wz中包含高版本装备和物品，所以导致校验失效。
尽管装备可以使用ItemInformationProvider.getInstance().getEquipById(itemId)来判断，但是发送道具可能仍有问题。
为避免后续出现类似问题，还是需要保证String.wz的准确性。需要将wz-zh-CN下的String.wz同原版wz下的String.wz做对比，如果是原版不存在的东西，需要进行删除，如存在汉化可以保留。
@SleepNap @leevccc @huash @jarecl @yainse @SpicyBurgerKing @TokyoEric @stanx5

**Comment by SleepNap** [comment]
- [ ] Cash.img.xml
- [ ] Consume.img.xml
- [ ] Eqp.img.xml
- [ ] Etc.img.xml
- [ ] EULA.img.xml
- [ ] GLcloneC.img.xml
- [ ] GuestEULA.img.xml
- [ ] Ins.img.xml
- [ ] Map.img.xml
- [ ] Mob.img.xml
- [ ] MonsterBook.img.xml
- [ ] NameChange.img.xml
- [ ] Npc.img.xml
- [ ] Pet.img.xml
- [ ] PetDialog.img.xml
- [ ] Skill.img.xml
- [ ] TestEULA.img.xml
- [ ] ToolTipHelp.img.xml
- [ ] TransferWorld.img.xml
- [ ] TrialEULA.img.xml

**Comment by Tomddlee** [comment]
Tks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BeiDouMS/BeiDou-Server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月15日(星期四) 上午9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BeiDouMS/BeiDou-Server] 管理端装备发放问题 (Issue #43)





  
 Cash.img.xml
 
 Consume.img.xml
 
 Eqp.img.xml
 
 Etc.img.xml
 
 EULA.img.xml
 
 GLcloneC.img.xml
 
 GuestEULA.img.xml
 
 Ins.img.xml
 
 Map.img.xml
 
 Mob.img.xml
 
 MonsterBook.img.xml
 
 NameChange.img.xml
 
 Npc.img.xml
 
 Pet.img.xml
 
 PetDialog.img.xml
 
 Skill.img.xml
 
 TestEULA.img.xml
 
 ToolTipHelp.img.xml
 
 TransferWorld.img.xml
 
 TrialEULA.img.xml

**Comment by SleepNap** [comment]
已参考原英文String.wz校验完毕，去掉上述xml中高版本id
