### ISSUE TITLE
北斗的开发计划中有添加高版本的资源吗？

### ISSUE THREAD

**Issue by pwnhub1024** [BeiDouMS/BeiDou-Server#48]
我在hms的dc中发现了一个高版本的wz资源 可惜没有汉化
for the .img files if anyone needs them:
https://mega.nz/file/raZgEaib#Xp3BhaUMc2oLqgdWmNYrOqLJMIRSjwR2gV1WX6_Ga4w
https://drive.google.com/file/d/1AiD-atI4BsxudHrUx_b4OASMkaOCbF2f/view?usp=drive_link

**Comment by SleepNap** [comment]
会有，汪汪堡大佬已实现。但是是否会开源，关注后续动态把

**Comment by SpicyBurgerKing** [comment]
待北斗原客戶端穩定的情況下可以考慮分支添加高版本
