### ISSUE TITLE
商城道具bug&汉化、废都广场系列任务汉化、技能描述换行

### ISSUE THREAD

**Issue by TokyoEric** [BeiDouMS/BeiDou-Server#56]
1、废都广场任务汉化
![1 1](https://github.com/user-attachments/assets/5ff1417a-2174-4825-8f55-c0c8a200580a)
![1](https://github.com/user-attachments/assets/b9f652fc-355d-4b5b-b01d-3521d09c996d)
2、商城道具双倍爆率7（30天）无效，是否排查商城所有双倍倍率卡？
![2 1](https://github.com/user-attachments/assets/3f43c900-a738-403c-ab45-c7f3e3a32710)
![2 2](https://github.com/user-attachments/assets/24f199cf-fad7-44e7-a1de-589fa522a801)
![2](https://github.com/user-attachments/assets/81237d6e-a1f5-46a9-9a17-11bb45b10879)
3、战神技能描述未自动换行、所有职业精灵的祝福没有汉化
![3](https://github.com/user-attachments/assets/de159ca7-aa57-45bc-96dc-1f9806e1e8eb)
![5](https://github.com/user-attachments/assets/d615ac2f-766a-4958-8ad7-a202f59b7d4c)
4、商城子项汉化，如图
![4](https://github.com/user-attachments/assets/e6704a46-124c-4dda-8280-aaeffab08183)
5、BeiDouMS，登录界面Logo不知道被谁替换了，得改回去
![6](https://github.com/user-attachments/assets/b3ab54e7-4d81-4eb7-88de-966774ab8082)

**Comment by yainse** [comment]
5 已经修正

**Comment by g9502995** [comment]
2.是wz汉化的问题
他正确是6-10点AM

**Comment by TokyoEric** [comment]
1、废弃广场系列任务23个已完成汉化

**Comment by SleepNap** [comment]
4.商城汉化+任务分类汉化

**Comment by SleepNap** [comment]
6.排查一下
![Uploading 00be46e2119ddccaf58ba716819b438c.png…]()

**Comment by SleepNap** [comment]
问题6暂未复现，可能是以下问题
![image](https://github.com/user-attachments/assets/d29a7338-4651-4880-bcb3-f44c71f95763)
