### ISSUE TITLE
!spawn命令BUG

### ISSUE THREAD

**Issue by yainse** [BeiDouMS/BeiDou-Server#57]
使用!spawn生成怪物，如果使用!spawn 100100 20 生成20只绿蜗牛。
那么只有第一只能杀死，剩下19只会卡住，杀不死，也不会动。
![image](https://github.com/user-attachments/assets/8f78e4f9-64e0-4ea3-93da-eb6fb07c2932)

**Comment by SleepNap** [comment]
已修复
