### ISSUE TITLE
装备显示道具等级，经验 关闭之后还是在游戏内显示，想删除掉不显示。

### ISSUE THREAD

**Issue by Syifan1** [BeiDouMS/BeiDou-Server#62]
![QQ图片20240819101525](https://github.com/user-attachments/assets/7640fc1b-6cc6-4613-99c8-cdd9d476c27b)
![QQ图片20240819101555](https://github.com/user-attachments/assets/2a3640d8-3b0b-4f0a-b9dd-7b786b00484b)

**Comment by SleepNap** [comment]
![80602f7723da99b37aeb4b3b5825415c](https://github.com/user-attachments/assets/f8bfd40c-1abd-4b82-bcdd-6a1fb46bc786)
修改wz
