### ISSUE TITLE
在服务端或者脚本如何调用聊天栏喇叭消息?

### ISSUE THREAD

**Issue by pwnhub1024** [BeiDouMS/BeiDou-Server#63]
比如国服转蛋 左下角全服通告的那个消息
貌似有很多种颜色 希望可以告知一下

**Comment by SleepNap** [comment]
character.startMapEffect

**Comment by pwnhub1024** [comment]
我看了下这个好像是全图喇叭消息 需要传道具id
右下角的通告也是这个么 那种黄底 绿底 红底的消息

**Comment by pwnhub1024** [comment]
左下角的聊天区域

**Comment by SleepNap** [comment]
自己研究一下MaplePacketCreator.serverNotice

**Comment by pwnhub1024** [comment]
非常感谢，就是这个类。

**Comment by pwnhub1024** [comment]
尊敬的开发者，感谢您抽空回复我。
String msg = "【上线通告】欢迎" + player.getName() + "登录了北斗冒险岛。";
                for (Character p1 : c.getWorldServer().getPlayerStorage().getAllCharacters()) {
                    // 如果玩家在商城，将会以弹窗的形式发送，一堆弹窗会把玩家逼疯！
                    if (p1.getCashShop().isOpened()) {
                        continue;
                    }
                    p1.dropMessage(6, msg);
                }
我在PlayerLoggedinHandler.java中的handlePacket函数中编写了这些代码，实现了玩家上线之后通告全体在线玩家。
如果我想模拟喇叭消息，比如使用高质地喇叭、心脏喇叭 应该如何编写代码呢？
