### ISSUE TITLE
服务端内调用serverNotice模拟消息 文本重复

### ISSUE THREAD

**Issue by pwnhub1024** [BeiDouMS/BeiDou-Server#69]
我尝试在 PlayerLoggedinHandler.java 中的handlePacket 方法中添加了如下代码：
String welcomeMsg = "【上线通告】: 可爱的 " + player.getName() + " 来到了北斗冒险岛。让我们用热烈的掌声欢迎TA吧！";
Server.getInstance().broadcastMessage(c.getWorld(), PacketCreator.serverNotice(3, c.getChannel(), welcomeMsg));

但是会导致游戏呈现出来的消息文本重复，如下方图片，我不清楚是因为什么原因导致的。
![Uploading 微信截图_20240820225839.png…]()

**Comment by leevccc** [comment]
图片无法显示

**Comment by leevccc** [comment]
`String welcomeMsg = "【上线通告】: 可爱的 " + player.getName() + " 来到了北斗冒险岛。让我们用热烈的掌声欢迎TA吧！";`
改为
`String welcomeMsg = "【上线通告】 : 可爱的 " + player.getName() + " 来到了北斗冒险岛。让我们用热烈的掌声欢迎TA吧！";`

**Comment by pwnhub1024** [comment]
非常感谢。
