### ISSUE TITLE
70级朱丽叶副本的灰暗的研究室1有bug

### ISSUE THREAD

**Issue by Syifan1** [BeiDouMS/BeiDou-Server#75]
![bfa7abd0830cbfe8970161ccc66f718](https://github.com/user-attachments/assets/65e1a6a1-26d2-4fb7-979e-910ebf36c4e4)
人物走到这里的时候的，地图变暗，正常只有人物周边的一小圈能看到，但是现在这个小圈跟人物的位置发生了偏移

**Comment by leevccc** [comment]
已修复，等客户端更新

仅测试 926100201
