### ISSUE TITLE
任务bug&汉化一系列

### ISSUE THREAD

**Issue by TokyoEric** [BeiDouMS/BeiDou-Server#87]
1、明珠港NPC特奥的任务 奇怪的约翰未汉化
![1](https://github.com/user-attachments/assets/955d96bf-2048-447e-9387-4cd7c61f0a22)

2、时间神殿追忆者任务没有办法完成
![2](https://github.com/user-attachments/assets/e9ca5967-98c3-409e-ae06-6a8bb4d49c16)

3、任务“女神的宠物”， 弹完小星星后任务点完成无反应
![3](https://github.com/user-attachments/assets/3f89647c-a094-4f43-9d95-8c84243acafd)

4、流浪炼金术师制作召唤石和魔法石游戏会闪退
5、天空之城码头最右边的npc艺斯未汉化
![5](https://github.com/user-attachments/assets/98d6b131-39b4-422e-8a97-a9357be8d34f)

6、天空之城艾利杰的长觉任务无法正常弹奏
![6](https://github.com/user-attachments/assets/04189ebe-ee8b-4809-989d-b6f1160a033a)

7、阿里安特矿石制作未汉化
![7](https://github.com/user-attachments/assets/5d5bb8db-b47a-40ad-8ea7-340cc09b0888)

8、玩具城地图显示不全
![8](https://github.com/user-attachments/assets/56f2d3c5-0c1c-4003-b9a9-53351debacdd)

9、战神、骑士团新建人物的灯泡任务"来自北斗开发者的问候"会导致没有相应职业群任务
![10](https://github.com/user-attachments/assets/d5182af0-5c3a-43b1-a934-c91a6d968968)

10、未来之城（逆奥）任务未汉化
![11](https://github.com/user-attachments/assets/83920f3d-8182-4ee0-a41e-3b38ec68412d)

11、逆奥之城的boss任务需要多人组队才能进
![13](https://github.com/user-attachments/assets/da7a3a0e-34a4-463a-b723-4c20a796fa45)

12、昭和村NPC系列未汉化，亚希子、美代子、嘉美、勇助
![17](https://github.com/user-attachments/assets/8fa11045-01b8-4061-86f2-620c4af3e715)
![17-1](https://github.com/user-attachments/assets/0b4e2aed-c4cc-4c75-ac93-9bed9e67a337)
![17-2](https://github.com/user-attachments/assets/d67236bf-d160-4402-a4ac-5b06535e034d)
![17-3](https://github.com/user-attachments/assets/876e86fb-ac04-468a-909d-81693c727d86)
13、暴力熊任务未汉化，限制6人以上才能开始
![18](https://github.com/user-attachments/assets/4500d14f-c210-4c55-8a97-258ecd01bf53)

**Comment by SleepNap** [comment]
1、明珠港NPC特奥的任务 奇怪的约翰未汉化 @TokyoEric @yainse @huash 
2、时间神殿追忆者任务没有办法完成 @SleepNap @g9502995 
3、任务“女神的宠物”， 弹完小星星后任务点完成无反应 @g9502995 @SleepNap 
4、流浪炼金术师制作召唤石和魔法石游戏会闪退 @SleepNap 
5、天空之城码头最右边的npc艺斯未汉化 @TokyoEric @yainse @huash 
6、天空之城艾利杰的长觉任务无法正常弹奏 @g9502995 @SleepNap 
7、阿里安特矿石制作未汉化 @TokyoEric @yainse @huash 
8、玩具城地图显示不全 @SpicyBurgerKing @leevccc 
9、战神、骑士团新建人物的灯泡任务"来自北斗开发者的问候"会导致没有相应职业群任务 @SpicyBurgerKing 
10、未来之城（逆奥）任务未汉化 @TokyoEric @yainse @huash 
11、逆奥之城的boss任务需要多人组队才能进 @智囊团
12、昭和村NPC系列未汉化，亚希子、美代子、嘉美、勇助 @TokyoEric @yainse @huash 
13、暴力熊任务未汉化，限制6人以上才能开始 @TokyoEric @yainse @huash @智囊团 @SleepNap

**Comment by yainse** [comment]
2已经和玩家确认，时间神殿任务流程可以正常走通。

**Comment by g9502995** [comment]
3.测试后可以正常完成

**Comment by TokyoEric** [comment]
5、7 已完成汉化

**Comment by TokyoEric** [comment]
10、11、12已汉化

**Comment by SleepNap** [comment]
1已修复

**Comment by SleepNap** [comment]
8.我看了几个端，也看过wiki这个地图没问题
![image](https://github.com/user-attachments/assets/710875ea-fe48-41b8-b3eb-25ad1ad39600)

**Comment by SleepNap** [comment]
13已汉化
