### ISSUE TITLE
战神职业系列专题任务BUG、无法完成、无法接取

### ISSUE THREAD

**Issue by TokyoEric** [BeiDouMS/BeiDou-Server#88]
战神出生救人任务后 过场动画无法跳过
战神二转任务部分任务未汉化
战神领取蘑菇王国任务及回复任务未汉化
战神职业任务 射手村NPC布鲁斯任务"第一次情报搜集完成"未完全汉化
战神职业任务 魔法密林NPC 妖精罗雯任务"第二次情报搜集完成"未完全汉化
战神职业任务 灯泡任务"人偶师的邀请"未完全汉化
战神职业任务 明珠港情报店NPC 特鲁任务"人偶师的警告"无法接取
战神职业任务 林中之城NPC日吉任务"人偶师的洞穴"无法完成
战神三转任务无法提交

![15](https://github.com/user-attachments/assets/c6e03148-138d-4f99-b2db-169f0de7e89f)
![15 1](https://github.com/user-attachments/assets/1d3a3c1c-4c99-4020-a493-3e415a6de0b1)
![15 2](https://github.com/user-attachments/assets/2a92339c-bb36-4a8d-b3fe-aa6e6682a171)
![15 3](https://github.com/user-attachments/assets/d9ea22d0-06c5-4435-8d44-e1615faa67d2)
![15 4](https://github.com/user-attachments/assets/1bffdb0f-7faf-4b1e-8eb2-3fb8b98961a1)
![15 5](https://github.com/user-attachments/assets/40994c82-4c74-4d89-9c93-9e7c479e4e78)
![15 6](https://github.com/user-attachments/assets/12301e1b-c2f6-48b0-b76d-177f9d18099a)
![15 7](https://github.com/user-attachments/assets/155c6ae8-2f43-4cce-8df8-0677d69ba494)
![15 8](https://github.com/user-attachments/assets/97ab5279-5b2f-4e36-b23e-e2c3f94beb00)

**Comment by SleepNap** [comment]
特殊职业是否修复？ @leevccc @SpicyBurgerKing

**Comment by SleepNap** [comment]
暂不修复，增加参数，默认不允许创建特殊职业
![image](https://github.com/user-attachments/assets/19eec9e9-d12f-4683-a962-7f2852b89dfd)

**Comment by JumpingY** [comment]
> 战神出生救人任务后 过场动画无法跳过 战神二转任务部分任务未汉化 战神领取蘑菇王国任务及回复任务未汉化 战神职业任务 射手村NPC布鲁斯任务"第一次情报搜集完成"未完全汉化 战神职业任务 魔法密林NPC 妖精罗雯任务"第二次情报搜集完成"未完全汉化 战神职业任务 灯泡任务"人偶师的邀请"未完全汉化 战神职业任务 明珠港情报店NPC 特鲁任务"人偶师的警告"无法接取 战神职业任务 林中之城NPC日吉任务"人偶师的洞穴"无法完成 战神三转任务无法提交
> 
> ![15](https://github.com/user-attachments/assets/c6e03148-138d-4f99-b2db-169f0de7e89f) ![15 1](https://github.com/user-attachments/assets/1d3a3c1c-4c99-4020-a493-3e415a6de0b1) ![15 2](https://github.com/user-attachments/assets/2a92339c-bb36-4a8d-b3fe-aa6e6682a171) ![15 3](https://github.com/user-attachments/assets/d9ea22d0-06c5-4435-8d44-e1615faa67d2) ![15 4](https://github.com/user-attachments/assets/1bffdb0f-7faf-4b1e-8eb2-3fb8b98961a1) ![15 5](https://github.com/user-attachments/assets/40994c82-4c74-4d89-9c93-9e7c479e4e78) ![15 6](https://github.com/user-attachments/assets/12301e1b-c2f6-48b0-b76d-177f9d18099a) ![15 7](https://github.com/user-attachments/assets/155c6ae8-2f43-4cce-8df8-0677d69ba494) ![15 8](https://github.com/user-attachments/assets/97ab5279-5b2f-4e36-b23e-e2c3f94beb00)

三转雪人工匠这个任务我测试了下，第一次也是出现你这样的问题，然后我放弃雪人任务，再重新接雪人任务，再去左边地图重新打乌鸦，打死了不会掉宝石（因为你已经拿了），再对话雪人就能完成任务了，后续的任务收集素材锻造宝石一切正常完成三转，估计是第一次在判定击杀乌鸦的逻辑有问题？
