### ISSUE TITLE
bug提交

### ISSUE THREAD

**Issue by Doc-Huang** [BeiDouMS/BeiDou-Server#95]
1.北斗系统的网页中发放经验如果为负数，则会发放很多经验，本想着是倒扣经验的。不知道其他的发放如果为负数会怎么样。
2.获得过的勋章没有体现，是不是BUG？
![image](https://github.com/user-attachments/assets/6df649c9-5eb5-4336-bc5e-d710e79eb046)
3.蘑菇城：摩天楼4和另一个的地图名字不显示，显示成?????
![image](https://github.com/user-attachments/assets/55c79b5d-ce08-4c77-b9db-5307ad3828fd)
![image](https://github.com/user-attachments/assets/3d6dd6ac-9efa-4207-8a7a-1d6fd8367b8d)
4.蘑菇城的雪人BOSS只有灰色有打击声音，白色和金色没有打击声音
![image](https://github.com/user-attachments/assets/e8d02e5d-1cb6-4022-a778-7189e98795d7)
![image](https://github.com/user-attachments/assets/67f741ed-0350-47a3-afb2-3a4f89d92666)
5. 有些物品的描述太长，就显示不全了
![image](https://github.com/user-attachments/assets/8fd97186-4f5c-4c66-849f-d960457904bd)
6.有几个没有汉化的任务
![image](https://github.com/user-attachments/assets/6e8b61b2-0019-49f3-bb0a-357db4ddeac5)
![image](https://github.com/user-attachments/assets/89469721-9c5f-4c9c-a515-938c1e7292e8)
![image](https://github.com/user-attachments/assets/54e277af-2b6f-4581-903f-c918732c0985)
![image](https://github.com/user-attachments/assets/c762be0e-3c6e-41ba-95f2-9a62340c0851)

**Comment by SleepNap** [comment]
1.北斗系统的网页中发放经验如果为负数，则会发放很多经验，本想着是倒扣经验的。不知道其他的发放如果为负数会怎么样。 --最新版本已不支持发负数
2.获得过的勋章没有体现，是不是BUG？ @leevccc 
3.蘑菇城：摩天楼4和另一个的地图名字不显示，显示成????? @yainse @huash @TokyoEric 
4.蘑菇城的雪人BOSS只有灰色有打击声音，白色和金色没有打击声音 @智囊团
5. 有些物品的描述太长，就显示不全了 -- 已经在改了，还没提交
6.有几个没有汉化的任务 @yainse @SleepNap @TokyoEric @huash

**Comment by leevccc** [comment]
用命令获取的勋章是不计入统计的。。。

**Comment by Doc-Huang** [comment]
> 用命令获取的勋章是不计入统计的。。。

我这个不是用命令获得的，我都是纯手动的，应该是哪个捐赠的枫叶老爷爷那里拿到的哦！

**Comment by TokyoEric** [comment]
3.蘑菇城地图命名问题已修复
6.楼中标出的任务已全部完成汉化
@SleepNap

**Comment by Kongwan333** [comment]
> 1.北斗系统的网页中发放经验如果为负数，则会发放很多经验，本想着是倒扣经验的。不知道其他的发放如果为负数会怎么样。 --最新版本已不支持发负数 2.获得过的勋章没有体现，是不是BUG？ @leevccc 3.蘑菇城：摩天楼4和另一个的地图名字不显示，显示成????? @yainse @huash @TokyoEric 4.蘑菇城的雪人BOSS只有灰色有打击声音，白色和金色没有打击声音 @智囊团 5. 有些物品的描述太长，就显示不全了 -- 已经在改了，还没提交 6.有几个没有汉化的任务 @yainse @SleepNap @TokyoEric @huash

![image](https://github.com/user-attachments/assets/5ab7d362-a20b-41bc-b3fb-8225880bed43)

其他栏物品描述信息展示问题已修正

**Comment by SleepNap** [comment]
2 4 无法复现或该问题已不存在
