### ISSUE TITLE
废弃都市地铁 无法到站 废都广场

### ISSUE THREAD

**Issue by xianyu-yuyu** [BeiDouMS/BeiDou-Server#97]
![QQ20240831-010009](https://github.com/user-attachments/assets/8f9a34a3-0479-41f8-8806-5f1d5d4b4716)
![QQ20240831-005725](https://github.com/user-attachments/assets/1ac6bfd9-5283-486a-8308-7075b271323c)
![QQ_1725037025158](https://github.com/user-attachments/assets/f9923d12-a814-4c98-8ff1-e59ef5be0880)

**Comment by TokyoEric** [comment]
实测该事件脚本没问题，请使用最新V12发行版本客户端

**Comment by SleepNap** [comment]
修复如果使用旅行倍率会导致报错的问题
