### ISSUE TITLE
雾海任务未汉化 系统任务无法接取点击没有反应

### ISSUE THREAD

**Issue by Jesse455823** [BeiDouMS/BeiDou-Server#98]
![QQ截图20240831104805](https://github.com/user-attachments/assets/bce28caf-74e1-4803-a5c0-f8950277cd31)

**Comment by SleepNap** [comment]
@SpicyBurgerKing @yainse @TokyoEric

**Comment by TokyoEric** [comment]
雾海任务已汉化

**Comment by TokyoEric** [comment]
雾海任务已汉化 @SleepNap
