### ISSUE TITLE
BUG提交

### ISSUE THREAD

**Issue by Doc-Huang** [BeiDouMS/BeiDou-Server#99]
蘑菇公主的任务无法接受？
![image](https://github.com/user-attachments/assets/9388e11c-1a16-41ac-bc3c-9211f7714548)
当身上有玉玺的时候不显示任务，玉玺丢了能够显示，但还是无法接收。
![image](https://github.com/user-attachments/assets/d8dc95e9-858b-4e8c-9798-2df77e1db96a)
![image](https://github.com/user-attachments/assets/8fa0c8bd-bbad-4ff6-a42d-97a77713f687)

这个旧战剑任务也有问题，怎么显示从GM这里接，跟实际的任务好像没有联系。
![image](https://github.com/user-attachments/assets/b65611a4-2745-49ce-a7df-6543adffb2fa)

任务还有好多没汉化：真的还有很多很多呢
![image](https://github.com/user-attachments/assets/b010c9e4-90a3-4edd-ad33-905bd0141f3c)
![image](https://github.com/user-attachments/assets/cafaf6c9-1769-48d7-9be5-998e08b5ba3c)
![image](https://github.com/user-attachments/assets/29a307b2-34a0-404d-a996-da1f02434662)
![image](https://github.com/user-attachments/assets/7181cb0c-e55e-431e-9885-19827fd92d5b)
![image](https://github.com/user-attachments/assets/bbd41132-e34e-4f30-b5c2-30f33a7f162e)
![image](https://github.com/user-attachments/assets/1e564457-0f2b-406c-8905-e7ddbef28c74)
![image](https://github.com/user-attachments/assets/ad37f28f-ad4a-4bb4-ba6f-33fe27d3b7f7)
![image](https://github.com/user-attachments/assets/2732fabc-11e0-456e-bb6a-165d0e02dc29)
![image](https://github.com/user-attachments/assets/e26e3ad6-3ba5-4691-b945-3ebc488685d3)
![image](https://github.com/user-attachments/assets/16de5baa-70ae-4a8c-8460-6a16e50103d4)

**Comment by SleepNap** [comment]
蘑菇公主的任务无法接受？ @yainse @TokyoEric 
当身上有玉玺的时候不显示任务，玉玺丢了能够显示，但还是无法接收。@yainse @TokyoEric @g9502995
这个旧战剑任务也有问题，怎么显示从GM这里接，跟实际的任务好像没有联系。 @yainse @TokyoEric 
任务还有好多没汉化：真的还有很多很多呢 -- 慢慢来

**Comment by SleepNap** [comment]
修复麦吉的旧战剑
